title: Virgin
default_lang: es
author:
  name: Bysidecar
  email: innovacion@bysidecar.com
  logo: ../../img/logo.png
taxonomies: [category, tag, author]
metadata:
  description: 'Virgin description'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
header:
  menu:
    menu1:
      text: GRAV.HEADER.MENU.MENU1.TEXT
      path: 'https://www.ofertasvirgin.es'
      active: true
      target: false
      self: false
    menu2:
      text: GRAV.HEADER.MENU.MENU2.TEXT
      path: 'https://www.ofertasvirgin.es/movil'
      active: false
      target: false
      self: false
    menu3:
      text: GRAV.HEADER.MENU.MENU3.TEXT
      path: 'https://www.ofertasvirgin.es/internet'
      active: false
      target: false
      self: false
    menu4:
      text: GRAV.HEADER.MENU.MENU4.TEXT
      path: '/blog'
      active: true
      target: false
      self: true