title: Virgin
default_lang: es
author:
  name: Bysidecar
  email: innovacion@bysidecar.com
  logo: ../../img/logo.png
taxonomies:
  - category
  - tag
metadata:
  description: 'Virgin description'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /blog: /
routes: null
blog:
  route: /blog
