apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: virgin-pre-bysidecar-me
  namespace: bysidecar-pre
spec:
  secretName: tls-virgin-pre-bysidecar-me
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: virgin-pre.bysidecar.me
  dnsNames:
  - virgin-pre.bysidecar.me
  acme:
    config:
    - dns01:
        provider: aws-route53
      domains:
      - virgin-pre.bysidecar.me