apiVersion: v1
kind: Service
metadata:
  namespace: bysidecar-pre
  name: virgin-blog-pre
spec:
  type: NodePort
  selector:
    app:  virgin-blog-pre
  ports:
  - name: http
    protocol: TCP
    port: 60100
    targetPort: 80